2024-01-23 16:07:05,914 - ERROR - connection handler failed
Traceback (most recent call last):
  File "E:\long\office-connector\Office-connector\venv\Lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "E:\long\office-connector\Office-connector\venv\Lib\site-packages\websockets\legacy\server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "E:\long\office-connector\Office-connector\lib\server.py", line 22, in handler
    id= ret.upload_id
        ^^^^^^^^^^^^^
AttributeError: 'DownLoadInfo' object has no attribute 'upload_id'
2024-01-23 16:07:05,930 - INFO - connection closed
2024-01-23 16:07:06,656 - INFO - server closing
2024-01-23 16:07:06,659 - INFO - server closed
2024-01-23 16:07:17,498 - INFO - server listening on 127.0.0.1:8765
2024-01-23 16:07:17,499 - INFO - server listening on [::1]:8765
2024-01-23 16:07:25,717 - INFO - server closing
2024-01-23 16:07:25,719 - INFO - server closed
2024-01-23 16:07:32,598 - INFO - server listening on 127.0.0.1:8765
2024-01-23 16:07:32,598 - INFO - server listening on [::1]:8765
2024-01-23 16:07:44,426 - INFO - connection open
2024-01-23 16:07:44,432 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default
2024-01-23 16:07:44,435 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\f2dd65ef-2fae-41bb-baee-9f82d198bb14.docx
2024-01-23 16:07:44,561 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\f2dd65ef-2fae-41bb-baee-9f82d198bb14.docx
2024-01-23 16:07:44,670 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\f2dd65ef-2fae-41bb-baee-9f82d198bb14.docx was sync to http://172.16.7.99/lvfile/api/default/files/update_source/f2dd65ef-2fae-41bb-baee-9f82d198bb14
2024-01-23 16:07:44,673 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\f2dd65ef-2fae-41bb-baee-9f82d198bb14.docx
2024-01-23 16:07:45,774 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default
2024-01-23 16:07:45,776 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\~$dd65ef-2fae-41bb-baee-9f82d198bb14.docx
2024-01-23 16:07:45,777 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\~$dd65ef-2fae-41bb-baee-9f82d198bb14.docx
2024-01-23 16:07:45,997 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default
2024-01-23 16:07:46,264 - ERROR - connection handler failed
Traceback (most recent call last):
  File "E:\long\office-connector\Office-connector\venv\Lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "E:\long\office-connector\Office-connector\venv\Lib\site-packages\websockets\legacy\server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "E:\long\office-connector\Office-connector\lib\server.py", line 22, in handler
    id= ret.upload_id
        ^^^^^^^^^^^^^
AttributeError: 'DownLoadInfo' object has no attribute 'upload_id'
2024-01-23 16:07:46,276 - INFO - connection closed
2024-01-23 16:07:55,292 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\~$dd65ef-2fae-41bb-baee-9f82d198bb14.docx
2024-01-23 16:07:57,118 - INFO - connection open
2024-01-23 16:07:57,128 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default
2024-01-23 16:07:57,249 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\86e35c79-bcf8-429f-98af-af0264b87e93.docx
2024-01-23 16:07:57,260 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\86e35c79-bcf8-429f-98af-af0264b87e93.docx
2024-01-23 16:07:58,252 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default
2024-01-23 16:07:58,254 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\~$e35c79-bcf8-429f-98af-af0264b87e93.docx
2024-01-23 16:07:58,255 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\~$e35c79-bcf8-429f-98af-af0264b87e93.docx
2024-01-23 16:07:58,460 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default
2024-01-23 16:07:58,507 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\86e35c79-bcf8-429f-98af-af0264b87e93.docx
2024-01-23 16:07:58,711 - ERROR - connection handler failed
Traceback (most recent call last):
  File "E:\long\office-connector\Office-connector\venv\Lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "E:\long\office-connector\Office-connector\venv\Lib\site-packages\websockets\legacy\server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "E:\long\office-connector\Office-connector\lib\server.py", line 22, in handler
    id= ret.upload_id
        ^^^^^^^^^^^^^
AttributeError: 'DownLoadInfo' object has no attribute 'upload_id'
2024-01-23 16:07:58,720 - INFO - connection closed
2024-01-23 16:08:09,199 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\~$e35c79-bcf8-429f-98af-af0264b87e93.docx
2024-01-23 16:08:17,950 - INFO - server closing
2024-01-23 16:08:17,951 - INFO - server closed
2024-01-23 16:18:10,102 - INFO - server listening on [::1]:8765
2024-01-23 16:18:10,103 - INFO - server listening on 127.0.0.1:8765
2024-01-23 16:18:15,300 - INFO - server closing
2024-01-23 16:18:15,303 - INFO - server closed
2024-01-23 16:18:21,493 - INFO - server listening on [::1]:8765
2024-01-23 16:18:21,494 - INFO - server listening on 127.0.0.1:8765
2024-01-23 16:18:24,000 - INFO - server closing
2024-01-23 16:18:24,002 - INFO - server closed
2024-01-23 16:18:55,906 - INFO - server listening on [::1]:8765
2024-01-23 16:18:55,906 - INFO - server listening on 127.0.0.1:8765
2024-01-23 16:19:09,440 - INFO - server closing
2024-01-23 16:19:09,441 - INFO - server closed
2024-01-23 16:19:57,994 - INFO - server listening on 127.0.0.1:8765
2024-01-23 16:19:57,995 - INFO - server listening on [::1]:8765
2024-01-23 16:20:06,793 - INFO - server closing
2024-01-23 16:20:06,795 - INFO - server closed
2024-01-23 16:24:58,963 - INFO - server listening on 127.0.0.1:8765
2024-01-23 16:24:58,964 - INFO - server listening on [::1]:8765
2024-01-23 16:25:02,904 - INFO - connection open
2024-01-23 16:25:03,328 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\e9f648cb-6ffb-4dd5-a53f-288dcca15e54.docx
2024-01-23 16:25:03,333 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\e9f648cb-6ffb-4dd5-a53f-288dcca15e54.docx
2024-01-23 16:25:04,462 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default
2024-01-23 16:25:04,464 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\~$f648cb-6ffb-4dd5-a53f-288dcca15e54.docx
2024-01-23 16:25:04,465 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\~$f648cb-6ffb-4dd5-a53f-288dcca15e54.docx
2024-01-23 16:25:04,560 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default
2024-01-23 16:25:04,610 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\e9f648cb-6ffb-4dd5-a53f-288dcca15e54.docx
2024-01-23 16:25:04,730 - ERROR - connection handler failed
Traceback (most recent call last):
  File "E:\long\office-connector\Office-connector\venv\Lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "E:\long\office-connector\Office-connector\venv\Lib\site-packages\websockets\legacy\server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "E:\long\office-connector\Office-connector\lib\server.py", line 22, in handler
    id= ret.upload_id
        ^^^^^^^^^^^^^
AttributeError: 'DownLoadInfo' object has no attribute 'upload_id'
2024-01-23 16:25:04,749 - INFO - connection closed
2024-01-23 16:25:07,876 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\~$f648cb-6ffb-4dd5-a53f-288dcca15e54.docx
2024-01-23 16:29:21,192 - INFO - server listening on [::1]:8765
2024-01-23 16:29:21,193 - INFO - server listening on 127.0.0.1:8765
2024-01-23 16:29:28,114 - INFO - connection open
2024-01-23 16:29:28,128 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default
2024-01-23 16:29:28,135 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\e9f648cb-6ffb-4dd5-a53f-288dcca15e54.docx
2024-01-23 16:29:28,270 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\e9f648cb-6ffb-4dd5-a53f-288dcca15e54.docx
2024-01-23 16:29:28,277 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\e9f648cb-6ffb-4dd5-a53f-288dcca15e54.docx
2024-01-23 16:29:29,324 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default
2024-01-23 16:29:29,327 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\~$f648cb-6ffb-4dd5-a53f-288dcca15e54.docx
2024-01-23 16:29:29,327 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default\~$f648cb-6ffb-4dd5-a53f-288dcca15e54.docx
2024-01-23 16:29:29,427 - INFO - C:\Users\admin.NTTLONG\AppData\Local\Codx-Desktop-Connector\data\default
2024-01-23 16:29:29,615 - ERROR - connection handler failed
Traceback (most recent call last):
  File "E:\long\office-connector\Office-connector\venv\Lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "E:\long\office-connector\Office-connector\venv\Lib\site-packages\websockets\legacy\server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "E:\long\office-connector\Office-connector\lib\server.py", line 22, in handler
    id= ret.upload_id
        ^^^^^^^^^^^^^
AttributeError: 'DownLoadInfo' object has no attribute 'upload_id'
